source 'http://rubygems.org'

gem 'rails', '3.2.8'

gem 'sqlite3'

gem 'devise'
gem 'cancan', github: 'ryanb/cancan', branch: '2.0'

gem 'haml-rails'
gem 'simple_form'
gem 'show_for'

gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'simple-navigation-bootstrap'

gem 'sass'

group :test do
  gem 'mocha', require: false
end

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  gem 'jquery-rails'
  gem 'bootstrap-sass'

  gem 'uglifier'
end

group :development do
  gem 'quiet_assets'
  gem 'letter_opener'#, github: 'jhawthorn/letter_opener'
end

group :production do
  gem 'exception_notification'
end
